### ISSUE TITLE
Minecraft 18.2 Forge - Failed to connect to server

### ISSUE THREAD

**Issue by jayyms** [DJWoodZ/Minecraft-Moon-Phase-Indicator#1]
Hello, 

Thank you for creating this mod! I am experiencing a problem when I add Moon Phase Indicator to my game. My game loads with no errors. However when I load my saved world, an error "Failed to connect to server" is displayed. Are there any conflicts with other mods? I am also using Enhanced Celestials? Or is this a server side mod?

Thanks!

**Comment by DJWoodZ** [comment]
Hello @jayyms,

Thank you for raising this issue. I'm sorry it isn't working for you. It looks like an issue with the Forge versions of this mod. It works in development, but the released version does not. I think it is just missing a single line of config. I will hopefully have a new version released soon. My apologies again.

**Comment by DJWoodZ** [comment]
Hello again @jayyms,

This should be fixed in v1.0.1, which you can download from the following websites:

* [CurseForge](https://www.curseforge.com/minecraft/mc-mods/moon-phase-indicator)
* [Modrinth](https://modrinth.com/mod/moon-phase-indicator)
